export const GET_STORIES = 'GET_STORIES';
export const SET_STORIES = 'SET_STORIES';

export const SET_SORTED_STORIES = 'SET_SORTED_STORIES';

export const SET_STORY = 'SET_STORY';

export const GET_CATEGORIES = 'GET_CATEGORIES';
export const SET_CATEGORIES = 'SET_CATEGORIES';
